describe('Game testing', () => {
  it('Play full match with winner X', () => {
    cy.visit('localhost:3000')
    cy.contains('Next player: X')
    cy.get('.game-board > :nth-child(2) > :nth-child(1)').click()
    cy.contains('Next player: O')
    cy.get('.game-board > :nth-child(2) > :nth-child(2)').click()
    cy.contains('Next player: X')
    cy.get(':nth-child(3) > :nth-child(2)').click()
    cy.contains('Next player: O')
    cy.get(':nth-child(3) > :nth-child(3)').click()
    cy.contains('Next player: X')
    cy.get(':nth-child(4) > :nth-child(3)').click()
    cy.contains('Winner: X')
    cy.contains('Parabéns jogador X, você venceu!')
  })

  it('Play full match with winner O', () => {
    cy.visit('localhost:3000')
    cy.contains('Next player: X')
    cy.get('.game-board > :nth-child(2) > :nth-child(1)').click()
    cy.contains('Next player: O')
    cy.get('.game-board > :nth-child(2) > :nth-child(2)').click()
    cy.contains('Next player: X')
    cy.get('.game-board > :nth-child(2) > :nth-child(3)').click()
    cy.contains('Next player: O')
    cy.get(':nth-child(3) > :nth-child(2)').click()
    cy.contains('Next player: X')
    cy.get('.game-board > :nth-child(3) > :nth-child(1)').click()
    cy.contains('Next player: O')
    cy.get(':nth-child(4) > :nth-child(2)').click()
    cy.contains('Winner: O')
    cy.contains('Parabéns jogador O, você venceu!')
  })
})